# Generated by Django 4.2.1 on 2023-05-10 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datacollector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023,
                    5,
                    10,
                    15,
                    5,
                    23,
                    877375,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
