# Generated by Django 4.2 on 2023-05-09 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datacollector", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
