# Generated by Django 4.2.1 on 2023-05-09 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datacollector", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 9, 18, 55, 36, 186644, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
