# Generated by Django 4.2.1 on 2023-05-09 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datacollector", "0002_remove_message_timestamp_message_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 9, 18, 57, 10, 35751, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
