# Generated by Django 4.2 on 2023-05-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
