# Generated by Django 4.2 on 2023-05-03 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0002_remove_message_id_alter_message_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
