# Generated by Django 4.2.2 on 2023-06-26 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("twitch_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="token",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_token",
                to="users.user",
            ),
        ),
    ]
